[package]
name = "advent-of-code"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.93", features = ["backtrace"] }
clap = { version = "4.5.21", features = ["derive", "string"] }
thiserror = "2.0.3"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
